import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "midnight-slate": "var(--color-midnight-slate)",
        "ghost-white": "var(--color-ghost-white)",
        "off-white-canvas": "var(--color-off-white-canvas)",
        "carbon-text": "var(--color-carbon-text)",
        "faded-steel": "var(--color-faded-steel)",
        "light-steel": "var(--color-light-steel)",
        "cosmic-gradient": "var(--color-cosmic-gradient)",
        "deep-space-black": "var(--color-deep-space-black)",
        border: "hsl(var(--border))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        surface: "hsl(var(--surface))",
        "surface-strong": "hsl(var(--surface-strong))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        input: "hsl(var(--input))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        success: "hsl(var(--success))",
        warning: "hsl(var(--warning))",
        info: "hsl(var(--info))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        ring: "hsl(var(--ring))",
        "chart-positive": "hsl(var(--chart-positive))",
        "chart-neutral": "hsl(var(--chart-neutral))",
        "chart-negative": "hsl(var(--chart-negative))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "var(--radius-xl)",
        sm: "var(--radius-md)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
        full: "var(--radius-full)",
      },
      fontFamily: {
        sans: ["var(--font-test-untitled-sans)"],
        display: ["var(--font-test-untitled-sans)"],
        inter: ["var(--font-inter)"],
      },
      fontSize: {
        caption: ["var(--text-caption)", { lineHeight: "var(--leading-caption)" }],
        "body-sm": ["var(--text-body-sm)", { lineHeight: "var(--leading-body-sm)" }],
        body: ["var(--text-body)", { lineHeight: "var(--leading-body)" }],
        subheading: ["var(--text-subheading)", { lineHeight: "var(--leading-subheading)" }],
        "heading-sm": ["var(--text-heading-sm)", { lineHeight: "var(--leading-heading-sm)" }],
        heading: ["var(--text-heading)", { lineHeight: "var(--leading-heading)" }],
        "heading-lg": ["var(--text-heading-lg)", { lineHeight: "var(--leading-heading-lg)" }],
        display: ["var(--text-display)", { lineHeight: "var(--leading-display)" }],
      },
    },
  },
  plugins: [],
};

export default config;
